# Generated by Django 6.0.5 on 2026-05-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='atendendente',
            new_name='atendente',
        ),
    ]
