# Generated by Django 6.0.5 on 2026-06-04 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_rename_atendendente_atendimento_atendente'),
        ('filas', '0011_categoria_contador_atual_categoria_ultima_data_reset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-iniciado_em']},
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='atendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='senha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='filas.senha'),
        ),
    ]
