# Generated by Django 6.0.5 on 2026-05-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Admin'), ('funcionario', 'Funcionário'), ('tv', 'TV'), ('totem', 'Totem')], max_length=20),
        ),
    ]
