# Generated by Django 6.0.5 on 2026-05-11 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('prioridade', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='filas.fila')),
            ],
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('cliente_nome', models.CharField(max_length=100)),
                ('cliente_telefone', models.CharField(max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('chamada_em', models.DateTimeField(blank=True, null=True)),
                ('Finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filas.categoria')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filas.fila')),
            ],
        ),
    ]
