# Generated by Django 6.0.5 on 2026-05-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senha',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='senha',
            old_name='Finalizado_em',
            new_name='finalizado_em',
        ),
        migrations.AddField(
            model_name='senha',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CHAMADA', 'Chamada'), ('EM_ATENDENDO', 'Em Atendendo'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO', max_length=20),
        ),
    ]
