# Generated by Django 4.2.7 on 2026-05-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0002_rename_categoria_senha_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='atendente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
