# Generated by Django 6.0.5 on 2026-05-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0003_senha_atendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='peso',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='categoria',
            name='prefixo',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tempo_estimado_max',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tempo_estimado_min',
            field=models.IntegerField(default=10),
        ),
    ]
