# Generated by Django 6.0.5 on 2026-05-14 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0004_categoria_peso_categoria_prefixo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
