# Generated by Django 6.0.5 on 2026-05-14 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0005_senha_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='senha',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CHAMADA', 'Chamada'), ('EM_ATENDENDO', 'Em Atendendo'), ('FINALIZADO', 'Finalizado'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='senha',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
