# Generated by Django 6.0.5 on 2026-05-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0006_senha_cliente_email_alter_senha_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senha',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
