# Generated by Django 6.0.5 on 2026-05-29 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0007_alter_senha_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacaoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('FECHOU', 'Fechou'), ('NAO_FECHOU', 'Não Fechou')], max_length=20, null=True)),
                ('tipo_evento', models.CharField(blank=True, choices=[('ANIVERSARIO', 'Aniversário'), ('CASAMENTO', 'Casamento'), ('FORMATURA', 'Formatura'), ('OUTRO', 'Outro')], max_length=20, null=True)),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('nomes_noivos', models.CharField(blank=True, max_length=255, null=True)),
                ('contato_noivos', models.CharField(blank=True, max_length=20, null=True)),
                ('universidade', models.CharField(blank=True, max_length=255, null=True)),
                ('curso', models.CharField(blank=True, max_length=255, null=True)),
                ('contato_formando', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo_nao_fechamento', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_impedimento', models.CharField(blank=True, max_length=255, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('senha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observacao', to='filas.senha')),
            ],
        ),
    ]
