# Generated by Django 6.0.5 on 2026-05-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0008_observacaoatendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacaoatendimento',
            name='motivo_impedimento',
        ),
        migrations.AddField(
            model_name='observacaoatendimento',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição adicional do atendimento', null=True),
        ),
        migrations.AddField(
            model_name='observacaoatendimento',
            name='nome_aniversariante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='observacaoatendimento',
            name='nome_cliente_observacao',
            field=models.CharField(blank=True, help_text='Nome do cliente fornecido na observação (quando tipo OUTRO)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='observacaoatendimento',
            name='tipo_evento_outro',
            field=models.CharField(blank=True, help_text="Descrição personalizada do tipo de evento quando 'OUTRO' é selecionado", max_length=255, null=True),
        ),
    ]
