# Generated by Django 6.0.5 on 2026-05-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0009_remove_observacaoatendimento_motivo_impedimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senha',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('CHAMADA', 'Chamada'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('FINALIZADO', 'Finalizado'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO', max_length=20),
        ),
    ]
