# Generated by Django 6.0.5 on 2026-06-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0010_alter_senha_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='contador_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoria',
            name='ultima_data_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='senha',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
