# Generated by Django 6.0.5 on 2026-06-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filas', '0011_categoria_contador_atual_categoria_ultima_data_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senha',
            name='tipo_locacao',
            field=models.CharField(blank=True, choices=[('locacao_noivo', 'Locação Noivo'), ('locacao_terno', 'Locação Terno'), ('locacao_infantil', 'Locação Infantil')], max_length=50, null=True),
        ),
    ]
